(defvar user-folder)
(defvar gk/prefix)
(defvar gk/implementation-folder)
(defvar gk/spec-folder)
(defvar gk/implementation-suffix)
(defvar gk/spec-suffix)
(setq username "joshg")
(setq user-folder (concat "/Users/" username "/"))
(setq gk/prefix (concat user-folder "repos/GitKraken/"))
(setq gk/implementation-folder "src/js/")
(setq gk/spec-folder "spec/unitTests/")
(setq gk/implementation-suffix ".js")
(setq gk/spec-suffix "-spec.js")
(setq gk/resources-folder "src/strings/")
