(setq split-width-threshold 115)
(setq split-height-threshold 80)

;; https://www.emacswiki.org/emacs/ToggleWindowSplit
(defun toggle-window-split ()
  "Toggle between horizontal and vertical split."
  (interactive)
  (if (= (count-windows) 2)
      (let* ((this-buffer (window-buffer))
             (next-buffer (window-buffer (next-window)))
             (this-edges (window-edges (selected-window)))
             (next-edges (window-edges (next-window)))
             (this-is-second-window (not (and (<= (car this-edges)
                                                  (car next-edges))
                                              (<= (cadr this-edges)
                                                  (cadr next-edges)))))
             (splitter
              (if (= (car this-edges)
                     (car (window-edges (next-window))))
                  'split-window-horizontally
                'split-window-vertically)))
        (delete-other-windows)
        (let ((first-window (selected-window)))
          (funcall splitter)
          (if this-is-second-window (other-window 1))
          (set-window-buffer (selected-window) this-buffer)
          (set-window-buffer (next-window) next-buffer)
          (select-window first-window)
          (if this-is-second-window (other-window 1))))))
(global-set-key (kbd "C-x |") 'toggle-window-split)
